{% set name = "diffpy.srreal" %}
{% set version = "v1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: d0e4e847e39689a6d552ed64579b3e1f6f8cfee31130f43f54e4395935f0947e

build:
  # we need egg_dir to avoid overlapping diffpy/__init__.py files.
  preserve_egg_dir: true
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - setuptools
    - scons
    - pip
    - numpy {{ numpy }}
    - libdiffpy
    - libboost-python-devel

  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x') }}
    - diffpy.structure
    - pyobjcryst
    - periodictable

test:
  # Python imports
  imports:
    - diffpy
    - diffpy.srreal
    - diffpy.srreal.tests

  requires:
    - pip
  commands:
    - pip check


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/diffpy/diffpy.srreal
  summary: Calculators for PDF, bond valence sum and other
    pair-interaction quantities.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://www.diffpy.org/doc/srreal
  dev_url: https://github.com/diffpy/diffpy.srreal

# See http://docs.continuum.io/conda/build.html
# for more information about meta.yaml.

extra:
  recipe-maintainers:
    - pavoljuhas
    - sbillinge
    - XiaohaoYang
    - Sparks29032
